[s3]
key="${AWS_ACCESS_KEY}"
secret="${AWS_SECRET_KEY}"
bucket="tantar"

[textract]
key="${AWS_ACCESS_KEY}"
secret="${AWS_SECRET_KEY}"

[lambda]
key="${AWS_ACCESS_KEY}"
secret="${AWS_SECRET_KEY}"


[app]
secret="${SECRET_KEY}"
url="${API_URL}"


[openai]
api_key="${OPENAI_API_KEY}"


[logfire]
logfire_token="${LOGFIRE_TOKEN}"
environment="${ENVIRONMENT}"

[pitantar]
url="${PITANTAR_URL}"


[pappers]
url="${PAPPERS_API_URL}"
key="${PAPPERS_API_KEY}"

