"""set file type nullable

Revision ID: 9f648142cce5
Revises: d4a3fb39aa67
Create Date: 2025-03-10 09:17:36.120540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f648142cce5"
down_revision: Union[str, None] = "d4a3fb39aa67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "type")
    op.add_column("file", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "type")
    op.add_column("file", sa.Column("type", sa.String(), nullable=False))
