"""set type optional in file table

Revision ID: d4a3fb39aa67
Revises: 875b5ea41671
Create Date: 2025-03-10 09:14:14.808191

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "d4a3fb39aa67"
down_revision: Union[str, None] = "875b5ea41671"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
