"""create graph tables

Revision ID: ebb5f70a5ce3
Revises: 9f648142cce5
Create Date: 2025-03-10 10:36:43.279909

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ebb5f70a5ce3'
down_revision: Union[str, None] = '9f648142cce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
